org: paulcothenet
app: climatechangemakers
service: mailchimp-to-airtable

provider:
  name: aws
  profile: perso
  region: us-west-2
  runtime: nodejs16.x

plugins:
  - serverless-plugin-typescript

functions:
  sync:
    handler: src/sync.handler
    environment:
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base}
      MAILCHIMP_API_KEY: ${ssm:/ccm/mailchimp/api_key}
    memorySize: 256
    timeout: 60
    # events:
    #   - schedule: rate(2 hours)
