org: paulcothenet
app: climatechangemakers
service: airtable-to-salesforce

provider:
  name: aws
  profile: perso
  region: us-west-2
  runtime: nodejs12.x

# plugins:
#   - serverless-plugin-typescript

# package:
#   exclude:
#     - node_modules/puppeteer/.local-chromium/**

functions:
  sync:
    handler: sync.handler
    environment:
      SLACK_TOKEN: ${ssm:/ccm/slack/token~true}
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key~true}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base~true}
      SALESFORCE_PASSWORD: ${ssm:/ccm/salesforce/password~true}
      SALESFORCE_SECURITY_TOKEN: ${ssm:/ccm/salesforce/security_token~true}
    memorySize: 256
    timeout: 60
    events:
      - schedule: rate(2 hours)
