org: madkudu
app: marketing-ops
service: engagement

plugins:
  - serverless-plugin-typescript
  # - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  role:
    'Fn::ImportValue': RoleLambdaExecution
  deploymentBucket:
    name: ${cf:lambdas.S3BucketLambdas}

package:
  exclude:
    - node_modules/aws-sdk/**

functions:
  salesforce:
    handler: ./src/index.handler
    # name: ghost
    description: Score engagement in Salesforce
    events:
      - schedule: rate(4 hours)
    memorySize: 128
    timeout: 900
