org: climatechangemakers
app: airtable-sync
service: pg-to-airtable

provider:
  name: aws
  profile: perso
  region: us-west-2
  runtime: nodejs16.x

plugins:
  - serverless-plugin-typescript

functions:
  sync:
    handler: src/sync.handler
    environment:
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base}
      PGUSER: ccm_readwrite
      PGPASSWORD: ${ssm:/ccm/pg/ccm_readwrite}
      PGHOST: ccm-db.c51ekbqkhdej.us-west-2.rds.amazonaws.com
      PGPORT: 5432
      PGDATABASE: postgres
    memorySize: 256
    timeout: 120
    events:
      - schedule: rate(24 hours)
