from enum import Enum, unique


@unique
class Action(Enum):
    PHONE_CALLS = "PHONE_CALLS"
    CONSTITUENT_CONTACT = "CONSTITUENT_CONTACT"
    PERSONAL_MEETING = "PERSONAL_MEETING"
    SOCIAL_MEDIA_CONTACT = "SOCIAL_MEDIA_CONTACT"
    TOWN_HALL = "TOWN_HALL"
    LOBBY_MEETING = "LOBBY_MEETING"
    RELATIONAL_ORGANIZING_PERSONAL_MESSAGE = "RELATIONAL_ORGANIZING_PERSONAL_MESSAGE"
    RELATIONAL_ORGANIZING_SOCIAL_MEDIA = "RELATIONAL_ORGANIZING_SOCIAL_MEDIA"
    BLOG_POST = "BLOG_POST"
    ARTICLE_BY_REPORTER = "ARTICLE_BY_REPORTER"
    PODCAST = "PODCAST"
    TV_BROADCAST = "TV_BROADCAST"
    LETTER_TO_THE_EDITOR = "LETTER_TO_THE_EDITOR"
    OP_ED = "OP_ED"
    EDITORIAL = "EDITORIAL"
    PERSONALIZED_TALKING_POINTS = "PERSONALIZED_TALKING_POINTS"
    PHONE_BANKING = "PHONE_BANKING"
    TEXT_BANKING = "TEXT_BANKING"
    FUNDRAISING = "FUNDRAISING"
    OTHER = "OTHER"
