org: climatechangemakers
app: airtable-sync
service: slack-to-airtable

provider:
  name: aws
  profile: perso
  region: us-west-2
  runtime: nodejs12.x

functions:
  sync:
    handler: src/sync.handler
    environment:
      SLACK_TOKEN: ${ssm:/ccm/slack/token}
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base}
    memorySize: 256
    timeout: 60
    events:
      - schedule: rate(2 hours)
  active:
    handler: active.handler
    environment:
      SLACK_TOKEN: ${ssm:/ccm/slack/token}
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base}
    memorySize: 256
    timeout: 600
    events:
      - schedule: rate(25 minutes)
  channels:
    handler: channels.handler
    environment:
      SLACK_TOKEN: ${ssm:/ccm/slack/token}
      AIRTABLE_API_KEY: ${ssm:/ccm/airtable/api_key}
      AIRTABLE_BASE: ${ssm:/ccm/airtable/base}
    memorySize: 256
    timeout: 360
    events:
      - schedule: rate(4 hours)
