CREATE TYPE action_source AS ENUM ('HOUR_OF_ACTION', 'ANYTIME_ACTION');
CREATE TYPE action_intent AS ENUM ('ADVOCACY', 'ELECTORAL');
CREATE TYPE action AS ENUM (
  'PHONE_CALLS',
  'CONSTITUENT_LETTERS',
  'PERSONAL_MEETING',
  'SOCIAL_MEDIA_CONTACT',
  'TOWN_HALL',
  'LOBBY_MEETING',
  'RELATIONAL_ORGANIZING_PERSONAL_MESSAGE',
  'RELATIONAL_ORGANIZING_SOCIAL_MEDIA',
  'BLOG_POST',
  'ARTICLE_BY_REPORTER',
  'PODCAST',
  'TV_BROADCAST',
  'LETTER_TO_THE_EDITOR',
  'OP_ED',
  'EDITORIAL'
);
CREATE TYPE audience AS ENUM (
  'PERSONAL_NETWORK',
  'POLICYMAKER',
  'INFLUENCER',
  'STAKEHOLDER',
  'PUBLIC'
)
CREATE TYPE hoa_event_type as ENUM (
  'ADVOCACY_CRAFT_TALKING_POINTS',
  'ADVOCACY_POLICYMAKER_OUTREACH',
  'ADVOCACY_KEY_STAKEHOLDER_AND_PUBLIC_OUTREACH',
  'ADVOCACY_CLIMATE_CONVERSATION',
  'ELECTORAL'
)

CREATE TABLE IF NOT EXISTS actions_raw (
  email CITEXT,
  full_name VARCHAR(256),
  date DATE NOT NULL,
  action action NOT NULL,
  intent action_intent NOT NULL,
  count INTEGER NOT NULL CHECK (count > 0),
  source action_source NOT NULL,
  audience audience NOT NULL,
  other_form_inputs JSONB
);

CREATE TABLE IF NOT EXISTS hoa_events (
  event_id SERIAL PRIMARY KEY,
  date DATE NOT NULL,
  week DATE NOT NULL,
  campaign VARCHAR(256) NOT NULL,
  type HOA_EVENT_TYPE NOT NULL
)

CREATE TABLE IF NOT EXISTS luma_attendance (
  event_id INTEGER FK events.event_id
  email CITEXT NOT NULL
  signedup_at TIMESTAMP
  has_joined_event BOOL

)
